### ISSUE TITLE
Final group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by rcqx** [jr-cast/bytecar#14]
LINK GH PROJECT --> https://github.com/users/jr-cast/projects/8/views/1

We are 3 people: 

- Hector
- Frank
- Jose Ramon

![image](https://user-images.githubusercontent.com/58822719/191614718-cc111b9e-6bad-4d52-b66b-9a9c2be41e49.png)

**Comment by vichuge** [comment]
Hi dear student, 

Good job so far!
You still need to work on some issues to prepare your project for the final evaluation, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Suggested changes
_Check the comments under the review._

- Almost all cards don't have a description, I kindly invite you to add one for every task.
<img width="727" alt="image" src="https://user-images.githubusercontent.com/20563252/191619213-12a8600f-7a35-4d10-9831-d7474a20db8f.png">


You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
